create schema if not exists test;

drop table if exists languages_text_example;

create table languages_text_example
(
    id integer generated by default as identity primary key,
    sample varchar(1000),
    language varchar(200)
);

comment on table languages_text_example is 'Фраза "Я тебя люблю" на разных языках мира';

create unique index languages_text_example_language_uniq on languages_text_example (lower(language));

alter table languages_text_example set schema test;
