create table person_name_dictionary
(
    id            integer generated by default as identity
        constraint person_name_dictionary_pkey
            primary key,
    name          varchar(255) not null
        constraint person_name_dictionary_name_check
            check (name != '' AND btrim(name) = name),
    gender        gender,
    name_translit varchar(255)
        constraint person_name_dictionary_name_translit_check
            check (name_translit != '' AND btrim(name_translit) = name_translit),
    popularity    real
        constraint person_name_dictionary_popularity_check
            check (popularity between 0 AND 1)
);

comment on table person_name_dictionary is 'Словарь имён для детектирования пола человека';

comment on column person_name_dictionary.name is 'Имя';
comment on column person_name_dictionary.gender is 'Пол';
comment on column person_name_dictionary.name_translit is 'Транслитерация функцией iuliia_translate_mosmetro()';
comment on column person_name_dictionary.popularity is 'Популярность всех имён относительно друг-друга. NULL приравнивается к 1';

create unique index person_name_dictionary2_lower_idx on person_name_dictionary (lower(name));
create index person_name_dictionary_lower_name_translit on person_name_dictionary (lower(name_translit));
